// <auto-generated />
using System;
using JPD.Demo.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JPD.Demo.Service.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190921025204_JPD.Demo.Service.Data.UserContext_v6")]
    partial class JPDDemoServiceDataUserContext_v6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250);

                    b.Property<int>("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<Guid>("UserId");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address","dbo");
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.Property<Guid>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Interest","dbo");
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.HasKey("UserId");

                    b.ToTable("User","dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("92618f3f-2e86-4135-b3ed-0b2747f1f11f"),
                            Age = (short)36,
                            FirstName = "Richard",
                            LastName = "Bennett"
                        },
                        new
                        {
                            UserId = new Guid("afc3a292-5c80-416f-80f6-15b2dca39d6f"),
                            Age = (short)81,
                            FirstName = "Charles",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("fa8349d1-c01d-4987-b65c-927aa28b8ec0"),
                            Age = (short)43,
                            FirstName = "John",
                            LastName = ""
                        },
                        new
                        {
                            UserId = new Guid("2990acb1-9b4f-46e6-a704-c0366c92ee6f"),
                            Age = (short)73,
                            FirstName = "Jessica",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("8ba1e42c-c8a1-4e34-8efd-6e653c27a785"),
                            Age = (short)81,
                            FirstName = "Thomas",
                            LastName = "Hayes"
                        },
                        new
                        {
                            UserId = new Guid("a6c737f0-fb14-43aa-b8c5-cce4ce2c389a"),
                            Age = (short)37,
                            FirstName = "Linda",
                            LastName = ""
                        },
                        new
                        {
                            UserId = new Guid("243110f7-e75a-414f-8d92-bbe9fdb16b59"),
                            Age = (short)76,
                            FirstName = "Jennifer",
                            LastName = "Collins"
                        },
                        new
                        {
                            UserId = new Guid("8e7deef3-f714-42e5-a58b-9387040b3da1"),
                            Age = (short)38,
                            FirstName = "Charles",
                            LastName = ""
                        },
                        new
                        {
                            UserId = new Guid("3d569047-2e36-437b-8aad-5b15bcacf3fc"),
                            Age = (short)44,
                            FirstName = "William",
                            LastName = "Reed"
                        },
                        new
                        {
                            UserId = new Guid("e2103de2-8ed8-43da-97d2-c35fdea1b861"),
                            Age = (short)71,
                            FirstName = "Pedro",
                            LastName = "Johnson"
                        },
                        new
                        {
                            UserId = new Guid("170b3b2a-4bf2-4fcb-8b54-e71f3b46ea20"),
                            Age = (short)48,
                            FirstName = "Patricia",
                            LastName = "Martin"
                        },
                        new
                        {
                            UserId = new Guid("41e8b279-5993-41f7-a680-4a0aa6dab817"),
                            Age = (short)62,
                            FirstName = "Juan",
                            LastName = "Collins"
                        },
                        new
                        {
                            UserId = new Guid("e346bd8e-c0f8-4202-a54d-1280ed8f723e"),
                            Age = (short)73,
                            FirstName = "Juan",
                            LastName = "Hall"
                        },
                        new
                        {
                            UserId = new Guid("3d0b2c13-5a68-4713-b49c-b7d9bde10cae"),
                            Age = (short)33,
                            FirstName = "Charles",
                            LastName = "Reed"
                        },
                        new
                        {
                            UserId = new Guid("d1869d29-594f-4540-aded-5e096e4047b7"),
                            Age = (short)23,
                            FirstName = "Martina",
                            LastName = "Rivera"
                        },
                        new
                        {
                            UserId = new Guid("3eee7d5a-10ab-4250-845d-5b5ccaf14414"),
                            Age = (short)34,
                            FirstName = "Catalina",
                            LastName = "Washington"
                        },
                        new
                        {
                            UserId = new Guid("5bafc8c4-7526-4de2-a07f-f29210241b6a"),
                            Age = (short)24,
                            FirstName = "Sara",
                            LastName = "Lee"
                        },
                        new
                        {
                            UserId = new Guid("94dcfc93-9560-4a63-b3c7-9f5e9b821229"),
                            Age = (short)47,
                            FirstName = "Martina",
                            LastName = "Johnson"
                        },
                        new
                        {
                            UserId = new Guid("6e05253a-3a54-4c03-8768-1f9b291d3f42"),
                            Age = (short)32,
                            FirstName = "Joseph",
                            LastName = "Diaz"
                        },
                        new
                        {
                            UserId = new Guid("8399dbaa-8d75-4be8-9fe7-7c4505b96ebd"),
                            Age = (short)65,
                            FirstName = "Evan",
                            LastName = "Watson"
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
