// <auto-generated />
using System;
using JPD.Demo.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JPD.Demo.Service.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190921041045_JPD.Demo.Service.Data.UserContext_v10")]
    partial class JPDDemoServiceDataUserContext_v10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250);

                    b.Property<int>("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<Guid>("UserId");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address","dbo");

                    b.HasData(
                        new
                        {
                            AddressId = new Guid("409c8980-8674-4a09-83d9-dffacbecf8b3"),
                            AddressLine1 = "PO Box 15458",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Northbrook",
                            State = "AR",
                            UserId = new Guid("d4bfac39-ff99-407c-a369-9ce00acc90af"),
                            ZipCode = "85003"
                        },
                        new
                        {
                            AddressId = new Guid("b85fa152-f7c9-488b-9eee-05d0d705a823"),
                            AddressLine1 = "4 Privet Drive",
                            AddressLine2 = "Apt 201",
                            AddressType = 2,
                            City = "",
                            State = "",
                            UserId = new Guid("d4bfac39-ff99-407c-a369-9ce00acc90af"),
                            ZipCode = "32003"
                        },
                        new
                        {
                            AddressId = new Guid("17b55639-68e9-4ea0-bd90-91d0c76a1ebe"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Springfield",
                            State = "UT",
                            UserId = new Guid("70cf0c3a-703b-4ef0-bcf2-73a3e2c945d1"),
                            ZipCode = "84101"
                        },
                        new
                        {
                            AddressId = new Guid("a35b4b44-c795-44ac-bc59-dc3d8420c8d3"),
                            AddressLine1 = "129 West 81st Street",
                            AddressLine2 = "",
                            AddressType = 2,
                            City = "Bountiful",
                            State = "CO",
                            UserId = new Guid("70cf0c3a-703b-4ef0-bcf2-73a3e2c945d1"),
                            ZipCode = "06001"
                        },
                        new
                        {
                            AddressId = new Guid("1be0497d-55ce-422a-83ff-79b740b7d2aa"),
                            AddressLine1 = "PO Box 49003",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Emerald City",
                            State = "AR",
                            UserId = new Guid("92344715-535b-4dc1-8474-43d3126a8f68"),
                            ZipCode = "06002"
                        },
                        new
                        {
                            AddressId = new Guid("3fa70c5f-2845-4ab7-9c55-e5635a3fd77c"),
                            AddressLine1 = "1313 Mockingbird Lane",
                            AddressLine2 = "Suite 305",
                            AddressType = 2,
                            City = "Gugan City",
                            State = "FL",
                            UserId = new Guid("92344715-535b-4dc1-8474-43d3126a8f68"),
                            ZipCode = "19706"
                        },
                        new
                        {
                            AddressId = new Guid("4813c8d4-71c7-454f-8512-c91fcb21f5d3"),
                            AddressLine1 = "45 Spooner Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Mos Eisely",
                            State = "Ak",
                            UserId = new Guid("ebdef918-62ee-42e7-bc5b-e8649a736dab"),
                            ZipCode = "99501"
                        },
                        new
                        {
                            AddressId = new Guid("0df04f43-7b4a-4c80-810d-ab824a98fa24"),
                            AddressLine1 = "84 Beacon Street",
                            AddressLine2 = "Suite 305",
                            AddressType = 2,
                            City = "Emerald City",
                            State = "",
                            UserId = new Guid("ebdef918-62ee-42e7-bc5b-e8649a736dab"),
                            ZipCode = "32006"
                        },
                        new
                        {
                            AddressId = new Guid("9dcfcced-65fa-4a56-84b3-11ed38ebc8a3"),
                            AddressLine1 = "1202 Paper Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Godric's Hollow",
                            State = "UT",
                            UserId = new Guid("b39f333b-ef1d-44ea-93bd-ca0e1378b881"),
                            ZipCode = "80019"
                        },
                        new
                        {
                            AddressId = new Guid("f759f5e0-60da-43fe-a5fa-fcbdf40061fa"),
                            AddressLine1 = "124 Conch Street",
                            AddressLine2 = "Apt 4",
                            AddressType = 2,
                            City = "Springfield",
                            State = "UT",
                            UserId = new Guid("b39f333b-ef1d-44ea-93bd-ca0e1378b881"),
                            ZipCode = "35005"
                        },
                        new
                        {
                            AddressId = new Guid("87f003ae-8a7a-4a49-88c8-34ee1e030bbc"),
                            AddressLine1 = "PO Box 65478",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Cloud City",
                            State = "DE",
                            UserId = new Guid("a31dc996-8987-45e7-b39e-46fafd97c3f2"),
                            ZipCode = "71603"
                        },
                        new
                        {
                            AddressId = new Guid("7f4c85db-7ec2-4e8a-80cc-d3fcdaff1889"),
                            AddressLine1 = "2300 Shermer Road",
                            AddressLine2 = "Suite 305",
                            AddressType = 2,
                            City = "Northbrook",
                            State = "UT",
                            UserId = new Guid("a31dc996-8987-45e7-b39e-46fafd97c3f2"),
                            ZipCode = "35005"
                        },
                        new
                        {
                            AddressId = new Guid("fc3544d8-127c-4ab9-9d94-345859e830c6"),
                            AddressLine1 = "PO Box 15458",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Emerald City",
                            State = "CO",
                            UserId = new Guid("9da535ef-fc0d-4bac-9d58-1da7b8450757"),
                            ZipCode = "35006"
                        },
                        new
                        {
                            AddressId = new Guid("6cabb476-af29-4fe2-9363-24f461ddec35"),
                            AddressLine1 = "1882 Gerard Street",
                            AddressLine2 = "Apt 201",
                            AddressType = 2,
                            City = "Boulder",
                            State = "CO",
                            UserId = new Guid("9da535ef-fc0d-4bac-9d58-1da7b8450757"),
                            ZipCode = "99501"
                        },
                        new
                        {
                            AddressId = new Guid("bd0fe72c-b7cb-4649-96ba-a4007f37e9b6"),
                            AddressLine1 = "97 Rainey Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Springfield",
                            State = "CO",
                            UserId = new Guid("4745c343-d7e1-4b51-8b56-371e43075396"),
                            ZipCode = "35006"
                        },
                        new
                        {
                            AddressId = new Guid("e3eff32c-d50d-4aed-a99e-4b1deadcea86"),
                            AddressLine1 = "1313 Mockingbird Lane",
                            AddressLine2 = "Apt 201",
                            AddressType = 2,
                            City = "Boulder",
                            State = "Ak",
                            UserId = new Guid("4745c343-d7e1-4b51-8b56-371e43075396"),
                            ZipCode = "19702"
                        },
                        new
                        {
                            AddressId = new Guid("25628b45-3419-4ce5-bcfa-581e2718d03b"),
                            AddressLine1 = "PO Box 65478",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Gugan City",
                            State = "AZ",
                            UserId = new Guid("34d1c4ac-9e57-4cbf-a41c-380941622c7c"),
                            ZipCode = "90003"
                        },
                        new
                        {
                            AddressId = new Guid("33ef3193-93a8-4b40-bcfc-35053991e309"),
                            AddressLine1 = "2300 Shermer Road",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "Gugan City",
                            State = "AZ",
                            UserId = new Guid("34d1c4ac-9e57-4cbf-a41c-380941622c7c"),
                            ZipCode = "19702"
                        },
                        new
                        {
                            AddressId = new Guid("16953a96-d25c-492f-98dd-97bd8d72102d"),
                            AddressLine1 = "1 Avenue Q",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Metropolis",
                            State = "DE",
                            UserId = new Guid("1c8f3786-5268-4770-8db7-7f5c38dcdd2f"),
                            ZipCode = "99501"
                        },
                        new
                        {
                            AddressId = new Guid("31c62027-3b32-4e4f-9e58-d067c2a7b3c4"),
                            AddressLine1 = "4 Privet Drive",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "Metropolis",
                            State = "DE",
                            UserId = new Guid("1c8f3786-5268-4770-8db7-7f5c38dcdd2f"),
                            ZipCode = "35005"
                        },
                        new
                        {
                            AddressId = new Guid("6e2708c9-a7a2-437e-aa1d-9d62bf2fdc29"),
                            AddressLine1 = "PO Box 49003",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Emerald City",
                            State = "CO",
                            UserId = new Guid("17c46ec6-ceae-4398-a38e-ae168940270a"),
                            ZipCode = "84101"
                        },
                        new
                        {
                            AddressId = new Guid("327612bf-d8c6-4185-a42b-bc30f869714b"),
                            AddressLine1 = "1060 W Addison St.",
                            AddressLine2 = "Apt 4",
                            AddressType = 2,
                            City = "Northbrook",
                            State = "UT",
                            UserId = new Guid("17c46ec6-ceae-4398-a38e-ae168940270a"),
                            ZipCode = "99501"
                        },
                        new
                        {
                            AddressId = new Guid("aba816eb-e547-4578-8de6-fe6885dc1600"),
                            AddressLine1 = "173 Esses Drive",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "",
                            State = "",
                            UserId = new Guid("3abc042c-8404-445b-9eb5-9f79b5ab7fa1"),
                            ZipCode = ""
                        },
                        new
                        {
                            AddressId = new Guid("7f738495-52f5-4e67-869a-9cea50998a91"),
                            AddressLine1 = "3170 W. 53 Rd",
                            AddressLine2 = "5th Floor",
                            AddressType = 2,
                            City = "Winnetka",
                            State = "CO",
                            UserId = new Guid("3abc042c-8404-445b-9eb5-9f79b5ab7fa1"),
                            ZipCode = "80019"
                        },
                        new
                        {
                            AddressId = new Guid("f9585ddc-11f3-4f58-bee3-78e3d1e85373"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Emerald City",
                            State = "CA",
                            UserId = new Guid("3cf02614-c696-4e25-9b93-6653d1cef15a"),
                            ZipCode = "80019"
                        },
                        new
                        {
                            AddressId = new Guid("f541fe95-6e6c-44ee-9ad7-3ddd04ffa107"),
                            AddressLine1 = "711 Maple Street",
                            AddressLine2 = "5th Floor",
                            AddressType = 2,
                            City = "Copperton",
                            State = "CT",
                            UserId = new Guid("3cf02614-c696-4e25-9b93-6653d1cef15a"),
                            ZipCode = "99504"
                        },
                        new
                        {
                            AddressId = new Guid("859d31e7-30e8-4adf-8884-819979858307"),
                            AddressLine1 = "PO Box 49003",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Bountiful",
                            State = "DE",
                            UserId = new Guid("77cae637-b4be-4b85-bdda-b3325c2b692a"),
                            ZipCode = "84103"
                        },
                        new
                        {
                            AddressId = new Guid("b1738f42-1ce8-4034-93dc-ce0bf0343375"),
                            AddressLine1 = "84 Beacon Street",
                            AddressLine2 = "Apt 201",
                            AddressType = 2,
                            City = "Copperton",
                            State = "AZ",
                            UserId = new Guid("77cae637-b4be-4b85-bdda-b3325c2b692a"),
                            ZipCode = "85001"
                        },
                        new
                        {
                            AddressId = new Guid("be8c3ef7-0572-49a5-a07d-865998deeda8"),
                            AddressLine1 = "PO Box 49003",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Metropolis",
                            State = "UT",
                            UserId = new Guid("d49173ca-8449-4160-ac95-361e0166a482"),
                            ZipCode = "71602"
                        },
                        new
                        {
                            AddressId = new Guid("1bdb7abe-9f43-4845-9741-11ef6a874149"),
                            AddressLine1 = "84 Beacon Street",
                            AddressLine2 = "Apt 4",
                            AddressType = 2,
                            City = "Emerald City",
                            State = "DE",
                            UserId = new Guid("d49173ca-8449-4160-ac95-361e0166a482"),
                            ZipCode = "99501"
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.Property<Guid>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Interest","dbo");

                    b.HasData(
                        new
                        {
                            InterestId = new Guid("46c2698d-df0b-4f09-ad90-66aa416342b7"),
                            Description = "Dancing is my favorite thing to do.",
                            Name = "Dancing",
                            UserId = new Guid("d4bfac39-ff99-407c-a369-9ce00acc90af")
                        },
                        new
                        {
                            InterestId = new Guid("86f12794-e28c-4627-8516-2d177b1b48ab"),
                            Description = "Space Exploration, nuff said.",
                            Name = "Space Exploration",
                            UserId = new Guid("d4bfac39-ff99-407c-a369-9ce00acc90af")
                        },
                        new
                        {
                            InterestId = new Guid("65ddcfcc-062b-4492-afeb-124e1bcb86ae"),
                            Description = "I wish I could do more Traveling.",
                            Name = "Traveling",
                            UserId = new Guid("70cf0c3a-703b-4ef0-bcf2-73a3e2c945d1")
                        },
                        new
                        {
                            InterestId = new Guid("8e2ddaf0-f962-44bc-bf91-2968cca49c96"),
                            Description = "Skiing, nuff said.",
                            Name = "Skiing",
                            UserId = new Guid("70cf0c3a-703b-4ef0-bcf2-73a3e2c945d1")
                        },
                        new
                        {
                            InterestId = new Guid("bc94b174-9ee3-48f8-b234-e0872824a31e"),
                            Description = "I wish I could do more Space Exploration.",
                            Name = "Space Exploration",
                            UserId = new Guid("70cf0c3a-703b-4ef0-bcf2-73a3e2c945d1")
                        },
                        new
                        {
                            InterestId = new Guid("640b5ef3-a0fc-4384-ba1a-addeb89455d8"),
                            Description = "Reading is the best.",
                            Name = "Reading",
                            UserId = new Guid("92344715-535b-4dc1-8474-43d3126a8f68")
                        },
                        new
                        {
                            InterestId = new Guid("d09dab77-628c-452a-bf0f-ed664935aa7b"),
                            Description = "I wish I was better at Golf.",
                            Name = "Golf",
                            UserId = new Guid("ebdef918-62ee-42e7-bc5b-e8649a736dab")
                        },
                        new
                        {
                            InterestId = new Guid("08bfb373-5b32-4a9c-b592-106071b7f136"),
                            Description = "Space Exploration is the best.",
                            Name = "Space Exploration",
                            UserId = new Guid("ebdef918-62ee-42e7-bc5b-e8649a736dab")
                        },
                        new
                        {
                            InterestId = new Guid("d23fdc4f-47e9-49f9-9c87-f88e39419ac3"),
                            Description = "Fishing is my favorite thing to do.",
                            Name = "Fishing",
                            UserId = new Guid("b39f333b-ef1d-44ea-93bd-ca0e1378b881")
                        },
                        new
                        {
                            InterestId = new Guid("10d16bfe-9d24-4de8-a85b-4d9a08d0015b"),
                            Description = "Sofware Engineering Rocks!",
                            Name = "Sofware Engineering",
                            UserId = new Guid("a31dc996-8987-45e7-b39e-46fafd97c3f2")
                        },
                        new
                        {
                            InterestId = new Guid("bb402aa3-d5dc-4076-be95-0fbe085c0162"),
                            Description = "Reading, nuff said.",
                            Name = "Reading",
                            UserId = new Guid("a31dc996-8987-45e7-b39e-46fafd97c3f2")
                        },
                        new
                        {
                            InterestId = new Guid("730d7637-4718-440d-be37-9c486ea3d91d"),
                            Description = "I wish I was better at Volunteer Work.",
                            Name = "Volunteer Work",
                            UserId = new Guid("9da535ef-fc0d-4bac-9d58-1da7b8450757")
                        },
                        new
                        {
                            InterestId = new Guid("d04385f1-176e-477c-9d4f-b9d2224dd364"),
                            Description = "I wish I was better at Theater.",
                            Name = "Theater",
                            UserId = new Guid("9da535ef-fc0d-4bac-9d58-1da7b8450757")
                        },
                        new
                        {
                            InterestId = new Guid("acebe181-5552-4a1b-80d9-90705f8f54f2"),
                            Description = "I wish I was better at Traveling.",
                            Name = "Traveling",
                            UserId = new Guid("9da535ef-fc0d-4bac-9d58-1da7b8450757")
                        },
                        new
                        {
                            InterestId = new Guid("a868581f-2404-42d5-853b-d52c3666fcb4"),
                            Description = "Tennis is my favorite thing to do.",
                            Name = "Tennis",
                            UserId = new Guid("9da535ef-fc0d-4bac-9d58-1da7b8450757")
                        },
                        new
                        {
                            InterestId = new Guid("00bbe75f-c4fd-4e87-ad3d-40d875df463c"),
                            Description = "Painting is my favorite thing to do.",
                            Name = "Painting",
                            UserId = new Guid("9da535ef-fc0d-4bac-9d58-1da7b8450757")
                        },
                        new
                        {
                            InterestId = new Guid("b2438400-5265-44f1-a9c1-c85f9132b987"),
                            Description = "I not a big fan of Music.",
                            Name = "Music",
                            UserId = new Guid("4745c343-d7e1-4b51-8b56-371e43075396")
                        },
                        new
                        {
                            InterestId = new Guid("b3c7ce68-2365-4936-8766-c01b9be0a4d8"),
                            Description = "I wish I could do more Golf.",
                            Name = "Golf",
                            UserId = new Guid("4745c343-d7e1-4b51-8b56-371e43075396")
                        },
                        new
                        {
                            InterestId = new Guid("c3cf88c5-4bce-4f21-a409-7f08f0e5ca98"),
                            Description = "Bicycling is my favorite thing to do.",
                            Name = "Bicycling",
                            UserId = new Guid("4745c343-d7e1-4b51-8b56-371e43075396")
                        },
                        new
                        {
                            InterestId = new Guid("4ce99d9c-f501-4b8c-bd51-573881287289"),
                            Description = "I wish I could do more Space Exploration.",
                            Name = "Space Exploration",
                            UserId = new Guid("4745c343-d7e1-4b51-8b56-371e43075396")
                        },
                        new
                        {
                            InterestId = new Guid("63a1f4ae-6fc9-4bb8-b5b3-2aa4f82ea605"),
                            Description = "I wish I could do more Theater.",
                            Name = "Theater",
                            UserId = new Guid("34d1c4ac-9e57-4cbf-a41c-380941622c7c")
                        },
                        new
                        {
                            InterestId = new Guid("1e168f68-42ef-4939-9928-cacfe3259d49"),
                            Description = "Golf, nuff said.",
                            Name = "Golf",
                            UserId = new Guid("34d1c4ac-9e57-4cbf-a41c-380941622c7c")
                        },
                        new
                        {
                            InterestId = new Guid("60869b3a-3226-417c-8b9b-184f8731398e"),
                            Description = "Traveling, nuff said.",
                            Name = "Traveling",
                            UserId = new Guid("34d1c4ac-9e57-4cbf-a41c-380941622c7c")
                        },
                        new
                        {
                            InterestId = new Guid("956eca27-dfea-4698-acff-cf8b768f2afb"),
                            Description = "I not a big fan of Traveling.",
                            Name = "Traveling",
                            UserId = new Guid("34d1c4ac-9e57-4cbf-a41c-380941622c7c")
                        },
                        new
                        {
                            InterestId = new Guid("aaa42f48-e48f-4637-8ded-a724415a44e3"),
                            Description = "I wish I could do more Bicycling.",
                            Name = "Bicycling",
                            UserId = new Guid("1c8f3786-5268-4770-8db7-7f5c38dcdd2f")
                        },
                        new
                        {
                            InterestId = new Guid("ee84b474-da4b-45c3-a8b5-2a852e2dc76c"),
                            Description = "Space Exploration, nuff said.",
                            Name = "Space Exploration",
                            UserId = new Guid("1c8f3786-5268-4770-8db7-7f5c38dcdd2f")
                        },
                        new
                        {
                            InterestId = new Guid("4c7edd5f-68e9-4ae5-ba3e-a59f5c8b694c"),
                            Description = "I wish I could do more Painting.",
                            Name = "Painting",
                            UserId = new Guid("17c46ec6-ceae-4398-a38e-ae168940270a")
                        },
                        new
                        {
                            InterestId = new Guid("beb290c7-37e6-41d6-b378-f9f3e53bbaf2"),
                            Description = "I wish I was better at Hiking.",
                            Name = "Hiking",
                            UserId = new Guid("17c46ec6-ceae-4398-a38e-ae168940270a")
                        },
                        new
                        {
                            InterestId = new Guid("e348148c-085b-4aca-83cd-34389ff5371f"),
                            Description = "I wish I was better at Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("17c46ec6-ceae-4398-a38e-ae168940270a")
                        },
                        new
                        {
                            InterestId = new Guid("5ac4b727-f504-42ec-ac92-0eea1cfe168b"),
                            Description = "Reading, nuff said.",
                            Name = "Reading",
                            UserId = new Guid("17c46ec6-ceae-4398-a38e-ae168940270a")
                        },
                        new
                        {
                            InterestId = new Guid("c43092e6-8913-441f-915f-e39689a8f0d7"),
                            Description = "Tennis is the best.",
                            Name = "Tennis",
                            UserId = new Guid("17c46ec6-ceae-4398-a38e-ae168940270a")
                        },
                        new
                        {
                            InterestId = new Guid("ba43a57d-d368-4ce4-9aaa-e95a3bfff4fd"),
                            Description = "I wish I was better at Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("3abc042c-8404-445b-9eb5-9f79b5ab7fa1")
                        },
                        new
                        {
                            InterestId = new Guid("b92f5d1e-a274-44bf-9780-4490af10d6df"),
                            Description = "Reading is my favorite thing to do.",
                            Name = "Reading",
                            UserId = new Guid("3abc042c-8404-445b-9eb5-9f79b5ab7fa1")
                        },
                        new
                        {
                            InterestId = new Guid("a403063d-93fd-492b-92cb-54bbe7bcb95c"),
                            Description = "Caligraphy is the best.",
                            Name = "Caligraphy",
                            UserId = new Guid("3cf02614-c696-4e25-9b93-6653d1cef15a")
                        },
                        new
                        {
                            InterestId = new Guid("549bb4d6-d424-4f77-9764-9319ba13a316"),
                            Description = "Theater is the best.",
                            Name = "Theater",
                            UserId = new Guid("3cf02614-c696-4e25-9b93-6653d1cef15a")
                        },
                        new
                        {
                            InterestId = new Guid("6d1f581e-aad6-4929-9fdc-cc215331a006"),
                            Description = "I wish I was better at Traveling.",
                            Name = "Traveling",
                            UserId = new Guid("3cf02614-c696-4e25-9b93-6653d1cef15a")
                        },
                        new
                        {
                            InterestId = new Guid("22589e87-32c1-46e6-8715-9ba148be5437"),
                            Description = "I not a big fan of Fishing.",
                            Name = "Fishing",
                            UserId = new Guid("3cf02614-c696-4e25-9b93-6653d1cef15a")
                        },
                        new
                        {
                            InterestId = new Guid("4997856c-2499-4aec-af85-e0594f2390aa"),
                            Description = "Tennis is the best.",
                            Name = "Tennis",
                            UserId = new Guid("3cf02614-c696-4e25-9b93-6653d1cef15a")
                        },
                        new
                        {
                            InterestId = new Guid("7991e433-0fdb-4ff8-90ab-fa1995f379e0"),
                            Description = "I wish I was better at Fishing.",
                            Name = "Fishing",
                            UserId = new Guid("77cae637-b4be-4b85-bdda-b3325c2b692a")
                        },
                        new
                        {
                            InterestId = new Guid("ecd35e2b-39dc-47a7-bc79-71f791430f1a"),
                            Description = "I wish I was better at Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("77cae637-b4be-4b85-bdda-b3325c2b692a")
                        },
                        new
                        {
                            InterestId = new Guid("8b319bf4-5d91-44aa-9548-dfca183d78e7"),
                            Description = "Reading, nuff said.",
                            Name = "Reading",
                            UserId = new Guid("77cae637-b4be-4b85-bdda-b3325c2b692a")
                        },
                        new
                        {
                            InterestId = new Guid("79c4e09a-d733-4a2f-8611-4f7254e8376d"),
                            Description = "Sofware Engineering Rocks!",
                            Name = "Sofware Engineering",
                            UserId = new Guid("77cae637-b4be-4b85-bdda-b3325c2b692a")
                        },
                        new
                        {
                            InterestId = new Guid("05e93b5d-5028-4bc5-acbf-234c2c387554"),
                            Description = "Gardening, nuff said.",
                            Name = "Gardening",
                            UserId = new Guid("d49173ca-8449-4160-ac95-361e0166a482")
                        },
                        new
                        {
                            InterestId = new Guid("d5943288-4bb7-4b57-b977-8ef35e6dccbb"),
                            Description = "I enjoy Painting.",
                            Name = "Painting",
                            UserId = new Guid("d49173ca-8449-4160-ac95-361e0166a482")
                        },
                        new
                        {
                            InterestId = new Guid("151ad03e-c9d9-47db-adc0-59444151f9aa"),
                            Description = "Tennis, nuff said.",
                            Name = "Tennis",
                            UserId = new Guid("d49173ca-8449-4160-ac95-361e0166a482")
                        },
                        new
                        {
                            InterestId = new Guid("66faafee-ae71-4ef1-896f-f248c3163e6b"),
                            Description = "Mountain Climbing, nuff said.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("d49173ca-8449-4160-ac95-361e0166a482")
                        },
                        new
                        {
                            InterestId = new Guid("4fe9dc81-a2fc-4097-aee9-245b0d23645f"),
                            Description = "I wish I could do more Bicycling.",
                            Name = "Bicycling",
                            UserId = new Guid("d49173ca-8449-4160-ac95-361e0166a482")
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.HasKey("UserId");

                    b.ToTable("User","dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d4bfac39-ff99-407c-a369-9ce00acc90af"),
                            Age = (short)48,
                            FirstName = "Elizabeth",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("70cf0c3a-703b-4ef0-bcf2-73a3e2c945d1"),
                            Age = (short)50,
                            FirstName = "Evan",
                            LastName = "Bailey"
                        },
                        new
                        {
                            UserId = new Guid("92344715-535b-4dc1-8474-43d3126a8f68"),
                            Age = (short)75,
                            FirstName = "Patricia",
                            LastName = "Watson"
                        },
                        new
                        {
                            UserId = new Guid("ebdef918-62ee-42e7-bc5b-e8649a736dab"),
                            Age = (short)27,
                            FirstName = "Evan",
                            LastName = "Bennett"
                        },
                        new
                        {
                            UserId = new Guid("b39f333b-ef1d-44ea-93bd-ca0e1378b881"),
                            Age = (short)81,
                            FirstName = "Patricia",
                            LastName = "Washington"
                        },
                        new
                        {
                            UserId = new Guid("a31dc996-8987-45e7-b39e-46fafd97c3f2"),
                            Age = (short)37,
                            FirstName = "John",
                            LastName = "Anderson"
                        },
                        new
                        {
                            UserId = new Guid("9da535ef-fc0d-4bac-9d58-1da7b8450757"),
                            Age = (short)51,
                            FirstName = "Jennifer",
                            LastName = "Washington"
                        },
                        new
                        {
                            UserId = new Guid("4745c343-d7e1-4b51-8b56-371e43075396"),
                            Age = (short)45,
                            FirstName = "Pedro",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("34d1c4ac-9e57-4cbf-a41c-380941622c7c"),
                            Age = (short)78,
                            FirstName = "Evan",
                            LastName = "Lee"
                        },
                        new
                        {
                            UserId = new Guid("1c8f3786-5268-4770-8db7-7f5c38dcdd2f"),
                            Age = (short)71,
                            FirstName = "Evan",
                            LastName = "Hall"
                        },
                        new
                        {
                            UserId = new Guid("17c46ec6-ceae-4398-a38e-ae168940270a"),
                            Age = (short)74,
                            FirstName = "Pedro",
                            LastName = "Bailey"
                        },
                        new
                        {
                            UserId = new Guid("3abc042c-8404-445b-9eb5-9f79b5ab7fa1"),
                            Age = (short)34,
                            FirstName = "John",
                            LastName = ""
                        },
                        new
                        {
                            UserId = new Guid("3cf02614-c696-4e25-9b93-6653d1cef15a"),
                            Age = (short)59,
                            FirstName = "Patricia",
                            LastName = "Garcia"
                        },
                        new
                        {
                            UserId = new Guid("77cae637-b4be-4b85-bdda-b3325c2b692a"),
                            Age = (short)81,
                            FirstName = "Pedro",
                            LastName = "Martin"
                        },
                        new
                        {
                            UserId = new Guid("d49173ca-8449-4160-ac95-361e0166a482"),
                            Age = (short)82,
                            FirstName = "Richard",
                            LastName = "Clark"
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
