// <auto-generated />
using System;
using JPD.Demo.Service.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JPD.Demo.Service.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190921034704_JPD.Demo.Service.Data.UserContext_v8")]
    partial class JPDDemoServiceDataUserContext_v8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250);

                    b.Property<int>("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<Guid>("UserId");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address","dbo");

                    b.HasData(
                        new
                        {
                            AddressId = new Guid("f8f5eb9b-8bf5-4395-80cc-58b63fc535fe"),
                            AddressLine1 = "320 Fowler Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Gotham City",
                            State = "AR",
                            UserId = new Guid("4497aa79-4282-4936-97fd-741c4e6530f4"),
                            ZipCode = "71603"
                        },
                        new
                        {
                            AddressId = new Guid("1b2c3ca2-e214-424f-b8c1-1a85d5c5b7e2"),
                            AddressLine1 = "124 Conch Street",
                            AddressLine2 = "Apt 201",
                            AddressType = 2,
                            City = "Boulder",
                            State = "AR",
                            UserId = new Guid("4497aa79-4282-4936-97fd-741c4e6530f4"),
                            ZipCode = "84103"
                        },
                        new
                        {
                            AddressId = new Guid("33e40392-c0b3-42e5-b559-94f03276603c"),
                            AddressLine1 = "97 Rainey Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Copperton",
                            State = "AR",
                            UserId = new Guid("581e29b2-1918-4680-8474-83adcf8eee54"),
                            ZipCode = "32006"
                        },
                        new
                        {
                            AddressId = new Guid("bb9a6d75-9a03-446f-9bea-8c0c9adf4cd0"),
                            AddressLine1 = "2300 Shermer Road",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "Glenbrook North",
                            State = "AR",
                            UserId = new Guid("581e29b2-1918-4680-8474-83adcf8eee54"),
                            ZipCode = "80019"
                        },
                        new
                        {
                            AddressId = new Guid("f77c1872-15d3-43c2-a6de-ce97d575acba"),
                            AddressLine1 = "173 Esses Drive",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Godric's Hollow",
                            State = "CT",
                            UserId = new Guid("900a1854-3ad5-44ca-9908-67e0e2409266"),
                            ZipCode = "90003"
                        },
                        new
                        {
                            AddressId = new Guid("aacba728-b8fb-4b0e-a325-fef5815a726a"),
                            AddressLine1 = "370 Beech Street",
                            AddressLine2 = "",
                            AddressType = 2,
                            City = "Glenbrook North",
                            State = "",
                            UserId = new Guid("900a1854-3ad5-44ca-9908-67e0e2409266"),
                            ZipCode = "71603"
                        },
                        new
                        {
                            AddressId = new Guid("1315e82a-f856-4738-80cf-09133c87254f"),
                            AddressLine1 = "PO Box 45789",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Copperton",
                            State = "CT",
                            UserId = new Guid("5d42fee3-5472-4fcc-99f6-c3923e965250"),
                            ZipCode = "06002"
                        },
                        new
                        {
                            AddressId = new Guid("d31590e8-3922-47fe-a194-60304868d15d"),
                            AddressLine1 = "1882 Gerard Street",
                            AddressLine2 = "Suite 905",
                            AddressType = 2,
                            City = "Godric's Hollow",
                            State = "CO",
                            UserId = new Guid("5d42fee3-5472-4fcc-99f6-c3923e965250"),
                            ZipCode = "19702"
                        },
                        new
                        {
                            AddressId = new Guid("ec37ef95-2ead-4847-afd8-bd9266b087c1"),
                            AddressLine1 = "PO Box 15458",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Boulder",
                            State = "Ak",
                            UserId = new Guid("a26fac9d-f4d4-4b22-bf6e-fb986385fa49"),
                            ZipCode = "32003"
                        },
                        new
                        {
                            AddressId = new Guid("30aa8906-c87f-4c88-9c22-c59beeaed58c"),
                            AddressLine1 = "221B Baker Street",
                            AddressLine2 = "Apt 4",
                            AddressType = 2,
                            City = "Godric's Hollow",
                            State = "",
                            UserId = new Guid("a26fac9d-f4d4-4b22-bf6e-fb986385fa49"),
                            ZipCode = "06002"
                        },
                        new
                        {
                            AddressId = new Guid("c79c71ad-af50-4a5f-b074-2ae185e0df5c"),
                            AddressLine1 = "PO Box 15458",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Bryce Canyon City",
                            State = "",
                            UserId = new Guid("ba2e2f51-f476-4f00-8fc2-1a79b008f845"),
                            ZipCode = "99504"
                        },
                        new
                        {
                            AddressId = new Guid("a7bed3fd-8a22-4bfa-bbfd-2222b812d6f3"),
                            AddressLine1 = "9764 Jeoprardy Lane",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "Northbrook",
                            State = "Ak",
                            UserId = new Guid("ba2e2f51-f476-4f00-8fc2-1a79b008f845"),
                            ZipCode = "32003"
                        },
                        new
                        {
                            AddressId = new Guid("1a49ddf7-c78e-4faf-b35e-9b97d7bb4f06"),
                            AddressLine1 = "123 Sesame Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Winnetka",
                            State = "",
                            UserId = new Guid("75cf02a5-72a6-4a76-b994-b8607604a8bb"),
                            ZipCode = "35006"
                        },
                        new
                        {
                            AddressId = new Guid("3fb35481-7a08-43a4-86fd-48a929d43c34"),
                            AddressLine1 = "1407 Graymalkin Lane",
                            AddressLine2 = "Apt 201",
                            AddressType = 2,
                            City = "Godric's Hollow",
                            State = "FL",
                            UserId = new Guid("75cf02a5-72a6-4a76-b994-b8607604a8bb"),
                            ZipCode = ""
                        },
                        new
                        {
                            AddressId = new Guid("a1e6f652-ee90-4903-9c30-f55e6c3a9f5c"),
                            AddressLine1 = "PO Box 96325",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Godric's Hollow",
                            State = "",
                            UserId = new Guid("f7c33caf-d1fa-4c5f-ab73-fc394bfa4987"),
                            ZipCode = "90003"
                        },
                        new
                        {
                            AddressId = new Guid("479ca5e9-1d77-4c4b-a62f-baa4b6758f2b"),
                            AddressLine1 = "1313 Mockingbird Lane",
                            AddressLine2 = "Suite 305",
                            AddressType = 2,
                            City = "Glenbrook North",
                            State = "AR",
                            UserId = new Guid("f7c33caf-d1fa-4c5f-ab73-fc394bfa4987"),
                            ZipCode = "80011"
                        },
                        new
                        {
                            AddressId = new Guid("54834953-0ea8-4789-b62d-47ce2b9d3bb4"),
                            AddressLine1 = "565 N. Clinton Drive",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Metropolis",
                            State = "CT",
                            UserId = new Guid("e1e72fc3-cee0-490d-ab3a-86e087277445"),
                            ZipCode = "84103"
                        },
                        new
                        {
                            AddressId = new Guid("5b7ef291-a91b-477d-ab98-fc90896ca1bb"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            AddressType = 2,
                            City = "Winnetka",
                            State = "Ak",
                            UserId = new Guid("e1e72fc3-cee0-490d-ab3a-86e087277445"),
                            ZipCode = "85001"
                        },
                        new
                        {
                            AddressId = new Guid("4802c0ec-b957-4899-9dd9-5eede4ccbf24"),
                            AddressLine1 = "",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Metropolis",
                            State = "FL",
                            UserId = new Guid("d6cf4d49-c750-423a-976a-fdb28059b575"),
                            ZipCode = "80019"
                        },
                        new
                        {
                            AddressId = new Guid("02bd3d90-ea3f-4c56-802d-4361ae253dde"),
                            AddressLine1 = "1060 W Addison St.",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "Gugan City",
                            State = "DE",
                            UserId = new Guid("d6cf4d49-c750-423a-976a-fdb28059b575"),
                            ZipCode = "35006"
                        },
                        new
                        {
                            AddressId = new Guid("da086ffc-b307-4dc4-97a1-8a97edcce2ff"),
                            AddressLine1 = "PO Box 15458",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Glenbrook North",
                            State = "AR",
                            UserId = new Guid("af392293-7c53-4bc5-8702-d47145bd9279"),
                            ZipCode = "99504"
                        },
                        new
                        {
                            AddressId = new Guid("b3a42214-7e04-4081-b2f7-4dd4add25d48"),
                            AddressLine1 = "221B Baker Street",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "Metropolis",
                            State = "",
                            UserId = new Guid("af392293-7c53-4bc5-8702-d47145bd9279"),
                            ZipCode = "99501"
                        },
                        new
                        {
                            AddressId = new Guid("5be6fce9-932b-4ea1-8bbd-b9c02f8ee36f"),
                            AddressLine1 = "PO Box 15458",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Bountiful",
                            State = "DE",
                            UserId = new Guid("eb36fc66-6aad-4549-9aa8-758a4bbe6fd9"),
                            ZipCode = "80019"
                        },
                        new
                        {
                            AddressId = new Guid("9f064c66-9397-4d2f-8b37-7ab6573ee997"),
                            AddressLine1 = "124 Conch Street",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "Bountiful",
                            State = "Ak",
                            UserId = new Guid("eb36fc66-6aad-4549-9aa8-758a4bbe6fd9"),
                            ZipCode = "06001"
                        },
                        new
                        {
                            AddressId = new Guid("f95ec5a2-f94f-4b16-aab8-29c034fb79b6"),
                            AddressLine1 = "45 Spooner Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Bountiful",
                            State = "CO",
                            UserId = new Guid("c277e72a-4fb6-40ef-93e6-28209f3dc887"),
                            ZipCode = "85001"
                        },
                        new
                        {
                            AddressId = new Guid("c6e51598-9a58-4ae4-a75b-1b80272c997e"),
                            AddressLine1 = "714 Delaware",
                            AddressLine2 = "5th Floor",
                            AddressType = 2,
                            City = "Metropolis",
                            State = "CT",
                            UserId = new Guid("c277e72a-4fb6-40ef-93e6-28209f3dc887"),
                            ZipCode = "32006"
                        },
                        new
                        {
                            AddressId = new Guid("212333ef-2181-497f-b2af-cde486558788"),
                            AddressLine1 = "123 Sesame Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Winnetka",
                            State = "",
                            UserId = new Guid("e3bd4ccb-c1a9-459b-9931-2c60e53f858c"),
                            ZipCode = "90001"
                        },
                        new
                        {
                            AddressId = new Guid("96457da5-b29e-4c38-a937-932cff8fcd2a"),
                            AddressLine1 = "2300 Shermer Road",
                            AddressLine2 = "Suite 905",
                            AddressType = 2,
                            City = "Metropolis",
                            State = "AZ",
                            UserId = new Guid("e3bd4ccb-c1a9-459b-9931-2c60e53f858c"),
                            ZipCode = "35005"
                        },
                        new
                        {
                            AddressId = new Guid("41810494-4f08-4d84-ae24-69af7b9eb60a"),
                            AddressLine1 = "PO Box 49003",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Cloud City",
                            State = "UT",
                            UserId = new Guid("15c94293-f567-4a3e-8fcf-1788ece03dca"),
                            ZipCode = "90003"
                        },
                        new
                        {
                            AddressId = new Guid("c87e1cd2-c3c2-4a2c-90fb-d5ed2394ccb6"),
                            AddressLine1 = "4 Privet Drive",
                            AddressLine2 = "",
                            AddressType = 2,
                            City = "",
                            State = "AR",
                            UserId = new Guid("15c94293-f567-4a3e-8fcf-1788ece03dca"),
                            ZipCode = "35006"
                        },
                        new
                        {
                            AddressId = new Guid("41a021e5-0894-493d-81ef-eada30648ab6"),
                            AddressLine1 = "PO Box 15458",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Northbrook",
                            State = "CA",
                            UserId = new Guid("e0e06c1c-0c0b-4165-ae48-4513e88e3fde"),
                            ZipCode = "35006"
                        },
                        new
                        {
                            AddressId = new Guid("ce7eaa8a-5546-43ae-8bcb-b7794168ae58"),
                            AddressLine1 = "221B Baker Street",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "",
                            State = "CA",
                            UserId = new Guid("e0e06c1c-0c0b-4165-ae48-4513e88e3fde"),
                            ZipCode = ""
                        },
                        new
                        {
                            AddressId = new Guid("1fc8f200-8686-4b7b-9395-2eae18d52afb"),
                            AddressLine1 = "97 Rainey Street",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Gotham City",
                            State = "FL",
                            UserId = new Guid("d9a28cce-a902-49a3-96ca-27a05cac3f84"),
                            ZipCode = "99501"
                        },
                        new
                        {
                            AddressId = new Guid("7da843b3-c21c-4c66-9272-650abf20d1ff"),
                            AddressLine1 = "4 Privet Drive",
                            AddressLine2 = "Suite 905",
                            AddressType = 2,
                            City = "Gugan City",
                            State = "CT",
                            UserId = new Guid("d9a28cce-a902-49a3-96ca-27a05cac3f84"),
                            ZipCode = "90003"
                        },
                        new
                        {
                            AddressId = new Guid("615c587e-6cd6-499a-921f-7780b2f97913"),
                            AddressLine1 = "PO Box 45789",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Metropolis",
                            State = "Ak",
                            UserId = new Guid("5e7294ad-e5ce-4671-b1b2-005dea6fb320"),
                            ZipCode = "06002"
                        },
                        new
                        {
                            AddressId = new Guid("0ce10728-e11d-4bef-9370-b5d5365c648b"),
                            AddressLine1 = "",
                            AddressLine2 = "Apt 4",
                            AddressType = 2,
                            City = "Cloud City",
                            State = "DE",
                            UserId = new Guid("5e7294ad-e5ce-4671-b1b2-005dea6fb320"),
                            ZipCode = "19702"
                        },
                        new
                        {
                            AddressId = new Guid("68a297e0-c71c-4c9c-82ef-8a3c72a5b0c0"),
                            AddressLine1 = "1 Avenue Q",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Gugan City",
                            State = "CO",
                            UserId = new Guid("04708e13-c05e-405f-b4f0-e67c8daf2a9f"),
                            ZipCode = "19702"
                        },
                        new
                        {
                            AddressId = new Guid("aa4910cd-454e-48d9-be2b-58541a6e7458"),
                            AddressLine1 = "1313 Mockingbird Lane",
                            AddressLine2 = "Apartment 5A",
                            AddressType = 2,
                            City = "Springfield",
                            State = "AR",
                            UserId = new Guid("04708e13-c05e-405f-b4f0-e67c8daf2a9f"),
                            ZipCode = "84101"
                        },
                        new
                        {
                            AddressId = new Guid("8085ab1f-158f-4b4f-b38d-dfdb650aac1d"),
                            AddressLine1 = "1 Avenue Q",
                            AddressLine2 = "",
                            AddressType = 1,
                            City = "Gugan City",
                            State = "DE",
                            UserId = new Guid("60676a45-1a7c-479c-8c08-b99921d78699"),
                            ZipCode = "19702"
                        },
                        new
                        {
                            AddressId = new Guid("2dbaa1ac-6a92-4d85-87cb-a503be80d23a"),
                            AddressLine1 = "1060 W Addison St.",
                            AddressLine2 = "5th Floor",
                            AddressType = 2,
                            City = "Mos Eisely",
                            State = "AZ",
                            UserId = new Guid("60676a45-1a7c-479c-8c08-b99921d78699"),
                            ZipCode = "71603"
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.Property<Guid>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Interest","dbo");

                    b.HasData(
                        new
                        {
                            InterestId = new Guid("705d163f-d5dd-4b3a-8c74-fa2ba69a63e9"),
                            Description = "Theater, nuff said.",
                            Name = "Theater",
                            UserId = new Guid("4497aa79-4282-4936-97fd-741c4e6530f4")
                        },
                        new
                        {
                            InterestId = new Guid("78cfb777-7e01-4f30-8a37-279c5e8eb7de"),
                            Description = "Skiing is my favorite thing to do.",
                            Name = "Skiing",
                            UserId = new Guid("581e29b2-1918-4680-8474-83adcf8eee54")
                        },
                        new
                        {
                            InterestId = new Guid("bd18fef7-6024-476d-9c87-b808cb11026f"),
                            Description = "Singing Out Loud is the best.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("900a1854-3ad5-44ca-9908-67e0e2409266")
                        },
                        new
                        {
                            InterestId = new Guid("3a3671c1-fbb1-4b36-b1dd-4f6bb4d5c73c"),
                            Description = "I wish I was better at Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("900a1854-3ad5-44ca-9908-67e0e2409266")
                        },
                        new
                        {
                            InterestId = new Guid("8033581d-0059-4944-bf2d-65d975caaf8c"),
                            Description = "I not a big fan of .",
                            Name = "",
                            UserId = new Guid("900a1854-3ad5-44ca-9908-67e0e2409266")
                        },
                        new
                        {
                            InterestId = new Guid("7f711e2b-b30c-4faa-b4f3-f445fb90fbd2"),
                            Description = "I wish I could do more Bicycling.",
                            Name = "Bicycling",
                            UserId = new Guid("5d42fee3-5472-4fcc-99f6-c3923e965250")
                        },
                        new
                        {
                            InterestId = new Guid("dd24e0a7-69ba-4c4d-b9e3-5167bbf26522"),
                            Description = "I enjoy Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("5d42fee3-5472-4fcc-99f6-c3923e965250")
                        },
                        new
                        {
                            InterestId = new Guid("3f1e3235-904c-4be9-9e57-5021c44a6692"),
                            Description = "I wish I could do more .",
                            Name = "",
                            UserId = new Guid("5d42fee3-5472-4fcc-99f6-c3923e965250")
                        },
                        new
                        {
                            InterestId = new Guid("d84a1388-7c20-446d-b37b-6a4f1805feaa"),
                            Description = "Dancing, nuff said.",
                            Name = "Dancing",
                            UserId = new Guid("a26fac9d-f4d4-4b22-bf6e-fb986385fa49")
                        },
                        new
                        {
                            InterestId = new Guid("e0a5d523-f4e7-4939-98b6-cb0d96222ad0"),
                            Description = "I wish I could do more Volunteer Work.",
                            Name = "Volunteer Work",
                            UserId = new Guid("a26fac9d-f4d4-4b22-bf6e-fb986385fa49")
                        },
                        new
                        {
                            InterestId = new Guid("a3a088c4-5929-4494-8753-31dfdd0edecf"),
                            Description = "I not a big fan of Music.",
                            Name = "Music",
                            UserId = new Guid("a26fac9d-f4d4-4b22-bf6e-fb986385fa49")
                        },
                        new
                        {
                            InterestId = new Guid("3bfc2387-487f-42d9-ba37-4d35eddb1ae9"),
                            Description = "I not a big fan of Golf.",
                            Name = "Golf",
                            UserId = new Guid("a26fac9d-f4d4-4b22-bf6e-fb986385fa49")
                        },
                        new
                        {
                            InterestId = new Guid("a1920fa1-892a-46c9-85ad-7d799e79ffc4"),
                            Description = "I wish I could do more Reading.",
                            Name = "Reading",
                            UserId = new Guid("a26fac9d-f4d4-4b22-bf6e-fb986385fa49")
                        },
                        new
                        {
                            InterestId = new Guid("cab65f1b-736c-4b76-be3a-2f751d55cf6a"),
                            Description = "I wish I could do more Singing Out Loud.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("ba2e2f51-f476-4f00-8fc2-1a79b008f845")
                        },
                        new
                        {
                            InterestId = new Guid("e76cd8f0-6671-40ca-bd70-b07b3746d859"),
                            Description = "Space Exploration is my favorite thing to do.",
                            Name = "Space Exploration",
                            UserId = new Guid("ba2e2f51-f476-4f00-8fc2-1a79b008f845")
                        },
                        new
                        {
                            InterestId = new Guid("e54e8713-34e2-4b12-81bb-577319cd16f8"),
                            Description = "I wish I was better at Golf.",
                            Name = "Golf",
                            UserId = new Guid("ba2e2f51-f476-4f00-8fc2-1a79b008f845")
                        },
                        new
                        {
                            InterestId = new Guid("381153e0-379f-4a5f-b237-566493546f0c"),
                            Description = "Skiing, nuff said.",
                            Name = "Skiing",
                            UserId = new Guid("ba2e2f51-f476-4f00-8fc2-1a79b008f845")
                        },
                        new
                        {
                            InterestId = new Guid("f1cc5b40-27d2-4341-a69f-959652fc5316"),
                            Description = "Space Exploration is the best.",
                            Name = "Space Exploration",
                            UserId = new Guid("75cf02a5-72a6-4a76-b994-b8607604a8bb")
                        },
                        new
                        {
                            InterestId = new Guid("67400c2b-4622-463f-8ed9-ac13956d8c80"),
                            Description = "I wish I could do more Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("f7c33caf-d1fa-4c5f-ab73-fc394bfa4987")
                        },
                        new
                        {
                            InterestId = new Guid("45ef1fad-85a8-4bc7-97d7-5e6e5b46cd70"),
                            Description = "I wish I was better at Reading.",
                            Name = "Reading",
                            UserId = new Guid("f7c33caf-d1fa-4c5f-ab73-fc394bfa4987")
                        },
                        new
                        {
                            InterestId = new Guid("bd16b63e-3b0b-41d5-a8fe-3dda498b90bf"),
                            Description = "Sofware Engineering Rocks!",
                            Name = "Sofware Engineering",
                            UserId = new Guid("f7c33caf-d1fa-4c5f-ab73-fc394bfa4987")
                        },
                        new
                        {
                            InterestId = new Guid("6727f0d6-44c0-444a-9ed6-1fd1f906a007"),
                            Description = "I wish I was better at Bicycling.",
                            Name = "Bicycling",
                            UserId = new Guid("e1e72fc3-cee0-490d-ab3a-86e087277445")
                        },
                        new
                        {
                            InterestId = new Guid("6dca58eb-e94b-41e5-be0f-c5003b2f79fc"),
                            Description = "Tennis, nuff said.",
                            Name = "Tennis",
                            UserId = new Guid("e1e72fc3-cee0-490d-ab3a-86e087277445")
                        },
                        new
                        {
                            InterestId = new Guid("3060838b-ba36-4c91-8061-233e7c70e690"),
                            Description = "I enjoy Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("e1e72fc3-cee0-490d-ab3a-86e087277445")
                        },
                        new
                        {
                            InterestId = new Guid("f243d08b-2b87-4759-ab93-bd2e7ea63af1"),
                            Description = "Sofware Engineering Rocks!",
                            Name = "Sofware Engineering",
                            UserId = new Guid("d6cf4d49-c750-423a-976a-fdb28059b575")
                        },
                        new
                        {
                            InterestId = new Guid("d3c08fe5-1126-4dce-9373-91067fd81a17"),
                            Description = "Hiking is my favorite thing to do.",
                            Name = "Hiking",
                            UserId = new Guid("af392293-7c53-4bc5-8702-d47145bd9279")
                        },
                        new
                        {
                            InterestId = new Guid("f3682de8-6d76-4587-9b57-2deb2ccdd332"),
                            Description = "I wish I was better at Space Exploration.",
                            Name = "Space Exploration",
                            UserId = new Guid("af392293-7c53-4bc5-8702-d47145bd9279")
                        },
                        new
                        {
                            InterestId = new Guid("57d8d7b0-cd42-4ccc-9690-bd47af3f0e7f"),
                            Description = "I wish I was better at Reading.",
                            Name = "Reading",
                            UserId = new Guid("eb36fc66-6aad-4549-9aa8-758a4bbe6fd9")
                        },
                        new
                        {
                            InterestId = new Guid("30356757-c986-41a7-a564-0fbb6a18a190"),
                            Description = "Hiking, nuff said.",
                            Name = "Hiking",
                            UserId = new Guid("eb36fc66-6aad-4549-9aa8-758a4bbe6fd9")
                        },
                        new
                        {
                            InterestId = new Guid("f6bb7b93-f5a8-4f57-84c6-adcdcf16edb6"),
                            Description = "Painting is my favorite thing to do.",
                            Name = "Painting",
                            UserId = new Guid("eb36fc66-6aad-4549-9aa8-758a4bbe6fd9")
                        },
                        new
                        {
                            InterestId = new Guid("299fc3b2-d500-40a6-bba8-b49aff346453"),
                            Description = "Dancing is the best.",
                            Name = "Dancing",
                            UserId = new Guid("eb36fc66-6aad-4549-9aa8-758a4bbe6fd9")
                        },
                        new
                        {
                            InterestId = new Guid("0fda2d80-0e62-46c1-a6bf-f8fd3f2a4c83"),
                            Description = "Volunteer Work is the best.",
                            Name = "Volunteer Work",
                            UserId = new Guid("eb36fc66-6aad-4549-9aa8-758a4bbe6fd9")
                        },
                        new
                        {
                            InterestId = new Guid("45f04709-905e-43db-b4f5-dff4a4277cd7"),
                            Description = "I wish I was better at Fishing.",
                            Name = "Fishing",
                            UserId = new Guid("c277e72a-4fb6-40ef-93e6-28209f3dc887")
                        },
                        new
                        {
                            InterestId = new Guid("fecd7f40-ecf7-4d70-b5fc-fbd663b65853"),
                            Description = "I enjoy Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("c277e72a-4fb6-40ef-93e6-28209f3dc887")
                        },
                        new
                        {
                            InterestId = new Guid("35b2c4d7-d83f-4e6d-915f-324adfac7539"),
                            Description = "I enjoy Singing Out Loud.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("c277e72a-4fb6-40ef-93e6-28209f3dc887")
                        },
                        new
                        {
                            InterestId = new Guid("97205132-4edc-44ab-8214-6a070fafd868"),
                            Description = "Space Exploration is my favorite thing to do.",
                            Name = "Space Exploration",
                            UserId = new Guid("e3bd4ccb-c1a9-459b-9931-2c60e53f858c")
                        },
                        new
                        {
                            InterestId = new Guid("bba8e34c-2538-4b1b-b41c-38545495e53c"),
                            Description = "I wish I could do more Volunteer Work.",
                            Name = "Volunteer Work",
                            UserId = new Guid("e3bd4ccb-c1a9-459b-9931-2c60e53f858c")
                        },
                        new
                        {
                            InterestId = new Guid("08b43b43-5833-4260-997c-fb8d325ebf36"),
                            Description = "Sofware Engineering Rocks!",
                            Name = "Sofware Engineering",
                            UserId = new Guid("e3bd4ccb-c1a9-459b-9931-2c60e53f858c")
                        },
                        new
                        {
                            InterestId = new Guid("2115e1e1-2690-4eab-9a2c-c468942e6580"),
                            Description = "I enjoy Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("e3bd4ccb-c1a9-459b-9931-2c60e53f858c")
                        },
                        new
                        {
                            InterestId = new Guid("8d42cada-3d92-4b99-bde7-1452b0234190"),
                            Description = "I wish I could do more Tennis.",
                            Name = "Tennis",
                            UserId = new Guid("e3bd4ccb-c1a9-459b-9931-2c60e53f858c")
                        },
                        new
                        {
                            InterestId = new Guid("199add81-d8bf-4ed2-83eb-9cf570f34410"),
                            Description = "I wish I could do more Caligraphy.",
                            Name = "Caligraphy",
                            UserId = new Guid("15c94293-f567-4a3e-8fcf-1788ece03dca")
                        },
                        new
                        {
                            InterestId = new Guid("2d35386e-f4cb-46fa-b0ee-f5f7a8f8bdee"),
                            Description = "I wish I was better at Golf.",
                            Name = "Golf",
                            UserId = new Guid("15c94293-f567-4a3e-8fcf-1788ece03dca")
                        },
                        new
                        {
                            InterestId = new Guid("37fce4d3-ad8d-4edf-8d96-15167007f8e7"),
                            Description = "I wish I was better at Music.",
                            Name = "Music",
                            UserId = new Guid("15c94293-f567-4a3e-8fcf-1788ece03dca")
                        },
                        new
                        {
                            InterestId = new Guid("d5efa2b7-ef87-4a3e-a65e-5a9472ad5180"),
                            Description = "I enjoy .",
                            Name = "",
                            UserId = new Guid("15c94293-f567-4a3e-8fcf-1788ece03dca")
                        },
                        new
                        {
                            InterestId = new Guid("6e75ee94-ea94-4e13-abc3-c4ae379c6fa1"),
                            Description = "I enjoy Bicycling.",
                            Name = "Bicycling",
                            UserId = new Guid("e0e06c1c-0c0b-4165-ae48-4513e88e3fde")
                        },
                        new
                        {
                            InterestId = new Guid("72aa5512-8305-4da5-8dcb-14c01c70220a"),
                            Description = "Dancing is the best.",
                            Name = "Dancing",
                            UserId = new Guid("e0e06c1c-0c0b-4165-ae48-4513e88e3fde")
                        },
                        new
                        {
                            InterestId = new Guid("dd76356f-f28e-44b2-9abd-9ef47b153e61"),
                            Description = "Reading is my favorite thing to do.",
                            Name = "Reading",
                            UserId = new Guid("e0e06c1c-0c0b-4165-ae48-4513e88e3fde")
                        },
                        new
                        {
                            InterestId = new Guid("848c21ba-4148-4063-b638-9bbda457232d"),
                            Description = "Music, nuff said.",
                            Name = "Music",
                            UserId = new Guid("e0e06c1c-0c0b-4165-ae48-4513e88e3fde")
                        },
                        new
                        {
                            InterestId = new Guid("77a258ff-1497-4de1-bf26-090bf3556d7f"),
                            Description = "Music is my favorite thing to do.",
                            Name = "Music",
                            UserId = new Guid("d9a28cce-a902-49a3-96ca-27a05cac3f84")
                        },
                        new
                        {
                            InterestId = new Guid("2c711a3d-f94d-47b4-8320-77cc134df69d"),
                            Description = "Caligraphy is my favorite thing to do.",
                            Name = "Caligraphy",
                            UserId = new Guid("d9a28cce-a902-49a3-96ca-27a05cac3f84")
                        },
                        new
                        {
                            InterestId = new Guid("bd3ed382-b8f3-43e7-b039-2371828d8c01"),
                            Description = "I not a big fan of Reading.",
                            Name = "Reading",
                            UserId = new Guid("d9a28cce-a902-49a3-96ca-27a05cac3f84")
                        },
                        new
                        {
                            InterestId = new Guid("29fc2ef2-b678-41b5-9f2b-1a0605ee68ae"),
                            Description = "Golf, nuff said.",
                            Name = "Golf",
                            UserId = new Guid("d9a28cce-a902-49a3-96ca-27a05cac3f84")
                        },
                        new
                        {
                            InterestId = new Guid("2164285a-943e-4c9e-8690-d190b96b3ce0"),
                            Description = "I wish I was better at Music.",
                            Name = "Music",
                            UserId = new Guid("5e7294ad-e5ce-4671-b1b2-005dea6fb320")
                        },
                        new
                        {
                            InterestId = new Guid("17791899-40b1-4f76-a648-ffe091f41457"),
                            Description = "Singing Out Loud is the best.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("5e7294ad-e5ce-4671-b1b2-005dea6fb320")
                        },
                        new
                        {
                            InterestId = new Guid("f45e09a1-9f33-4953-9775-fa179661a8eb"),
                            Description = "I wish I was better at Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("5e7294ad-e5ce-4671-b1b2-005dea6fb320")
                        },
                        new
                        {
                            InterestId = new Guid("f66ef1cf-f222-4246-90a1-ce1274a715bf"),
                            Description = "Skiing is the best.",
                            Name = "Skiing",
                            UserId = new Guid("5e7294ad-e5ce-4671-b1b2-005dea6fb320")
                        },
                        new
                        {
                            InterestId = new Guid("1cc0db0b-ca50-4d75-bcc6-75a5a7d2ddf1"),
                            Description = "I wish I was better at Singing Out Loud.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("04708e13-c05e-405f-b4f0-e67c8daf2a9f")
                        },
                        new
                        {
                            InterestId = new Guid("db87aca2-ac97-4e80-8207-33355e1e714e"),
                            Description = "I wish I could do more Volunteer Work.",
                            Name = "Volunteer Work",
                            UserId = new Guid("04708e13-c05e-405f-b4f0-e67c8daf2a9f")
                        },
                        new
                        {
                            InterestId = new Guid("1f0a5f3a-5d55-4bb1-bcf4-3c44c7cf88b8"),
                            Description = "I enjoy Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("04708e13-c05e-405f-b4f0-e67c8daf2a9f")
                        },
                        new
                        {
                            InterestId = new Guid("372e60ec-933e-4f41-b715-8c0db891f3e9"),
                            Description = "I wish I was better at Space Exploration.",
                            Name = "Space Exploration",
                            UserId = new Guid("04708e13-c05e-405f-b4f0-e67c8daf2a9f")
                        },
                        new
                        {
                            InterestId = new Guid("4aff76ff-dde6-435c-bdb1-006e001d14a6"),
                            Description = "I not a big fan of Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("04708e13-c05e-405f-b4f0-e67c8daf2a9f")
                        },
                        new
                        {
                            InterestId = new Guid("0e609ef8-b426-4811-8a7c-40a912691f8f"),
                            Description = "I wish I was better at Painting.",
                            Name = "Painting",
                            UserId = new Guid("60676a45-1a7c-479c-8c08-b99921d78699")
                        },
                        new
                        {
                            InterestId = new Guid("c1fa26dd-6d4f-4ca6-a8f4-60a3a066cdb9"),
                            Description = "I wish I could do more Theater.",
                            Name = "Theater",
                            UserId = new Guid("60676a45-1a7c-479c-8c08-b99921d78699")
                        },
                        new
                        {
                            InterestId = new Guid("b93fdd6e-1a77-4a08-82bf-f9a25b9aff7f"),
                            Description = "Painting is the best.",
                            Name = "Painting",
                            UserId = new Guid("60676a45-1a7c-479c-8c08-b99921d78699")
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.HasKey("UserId");

                    b.ToTable("User","dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("4497aa79-4282-4936-97fd-741c4e6530f4"),
                            Age = (short)35,
                            FirstName = "Evan",
                            LastName = "Hall"
                        },
                        new
                        {
                            UserId = new Guid("581e29b2-1918-4680-8474-83adcf8eee54"),
                            Age = (short)64,
                            FirstName = "Charles",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("900a1854-3ad5-44ca-9908-67e0e2409266"),
                            Age = (short)18,
                            FirstName = "Barbara",
                            LastName = "Powell"
                        },
                        new
                        {
                            UserId = new Guid("5d42fee3-5472-4fcc-99f6-c3923e965250"),
                            Age = (short)49,
                            FirstName = "Charles",
                            LastName = "Roberts"
                        },
                        new
                        {
                            UserId = new Guid("a26fac9d-f4d4-4b22-bf6e-fb986385fa49"),
                            Age = (short)18,
                            FirstName = "William",
                            LastName = "Rivera"
                        },
                        new
                        {
                            UserId = new Guid("ba2e2f51-f476-4f00-8fc2-1a79b008f845"),
                            Age = (short)43,
                            FirstName = "Martina",
                            LastName = "Lee"
                        },
                        new
                        {
                            UserId = new Guid("75cf02a5-72a6-4a76-b994-b8607604a8bb"),
                            Age = (short)46,
                            FirstName = "",
                            LastName = "Garcia"
                        },
                        new
                        {
                            UserId = new Guid("f7c33caf-d1fa-4c5f-ab73-fc394bfa4987"),
                            Age = (short)47,
                            FirstName = "Mary",
                            LastName = "Anderson"
                        },
                        new
                        {
                            UserId = new Guid("e1e72fc3-cee0-490d-ab3a-86e087277445"),
                            Age = (short)62,
                            FirstName = "Sara",
                            LastName = "Rivera"
                        },
                        new
                        {
                            UserId = new Guid("d6cf4d49-c750-423a-976a-fdb28059b575"),
                            Age = (short)22,
                            FirstName = "Jessica",
                            LastName = "Watson"
                        },
                        new
                        {
                            UserId = new Guid("af392293-7c53-4bc5-8702-d47145bd9279"),
                            Age = (short)24,
                            FirstName = "Juan",
                            LastName = "Watson"
                        },
                        new
                        {
                            UserId = new Guid("eb36fc66-6aad-4549-9aa8-758a4bbe6fd9"),
                            Age = (short)26,
                            FirstName = "",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("c277e72a-4fb6-40ef-93e6-28209f3dc887"),
                            Age = (short)46,
                            FirstName = "Sara",
                            LastName = "Bennett"
                        },
                        new
                        {
                            UserId = new Guid("e3bd4ccb-c1a9-459b-9931-2c60e53f858c"),
                            Age = (short)46,
                            FirstName = "Catalina",
                            LastName = "Anderson"
                        },
                        new
                        {
                            UserId = new Guid("15c94293-f567-4a3e-8fcf-1788ece03dca"),
                            Age = (short)53,
                            FirstName = "Elizabeth",
                            LastName = "Bennett"
                        },
                        new
                        {
                            UserId = new Guid("e0e06c1c-0c0b-4165-ae48-4513e88e3fde"),
                            Age = (short)68,
                            FirstName = "Barbara",
                            LastName = "Anderson"
                        },
                        new
                        {
                            UserId = new Guid("d9a28cce-a902-49a3-96ca-27a05cac3f84"),
                            Age = (short)64,
                            FirstName = "Elizabeth",
                            LastName = "Rivera"
                        },
                        new
                        {
                            UserId = new Guid("5e7294ad-e5ce-4671-b1b2-005dea6fb320"),
                            Age = (short)25,
                            FirstName = "Charles",
                            LastName = ""
                        },
                        new
                        {
                            UserId = new Guid("04708e13-c05e-405f-b4f0-e67c8daf2a9f"),
                            Age = (short)62,
                            FirstName = "Linda",
                            LastName = "Roberts"
                        },
                        new
                        {
                            UserId = new Guid("60676a45-1a7c-479c-8c08-b99921d78699"),
                            Age = (short)58,
                            FirstName = "Sara",
                            LastName = ""
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
