// <auto-generated />
using System;
using JPD.Demo.Service.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JPD.Demo.Service.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190921024024_JPD.Demo.Service.Data.UserContext_v5")]
    partial class JPDDemoServiceDataUserContext_v5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250);

                    b.Property<int>("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<Guid>("UserId");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address","dbo");
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.Property<Guid>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Interest","dbo");
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.HasKey("UserId");

                    b.ToTable("User","dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("882d359b-97d6-4e1f-8e38-26239734e132"),
                            Age = (short)76,
                            FirstName = "Jennifer",
                            LastName = "Garcia"
                        },
                        new
                        {
                            UserId = new Guid("263e313b-e9f3-4afc-87d2-f008e6fda1f4"),
                            Age = (short)82,
                            FirstName = "Linda",
                            LastName = "Reed"
                        },
                        new
                        {
                            UserId = new Guid("c3b2da91-e1b1-4e3a-8c48-fde7d09f39b0"),
                            Age = (short)59,
                            FirstName = "Elizabeth",
                            LastName = "Collins"
                        },
                        new
                        {
                            UserId = new Guid("a39cd005-878a-446e-b3d7-25f6ffc46437"),
                            Age = (short)72,
                            FirstName = "Juan",
                            LastName = "Diaz"
                        },
                        new
                        {
                            UserId = new Guid("4fd8e3ea-c762-4a00-9f5a-8b4e0b9529e0"),
                            Age = (short)75,
                            FirstName = "Jessica",
                            LastName = "Hall"
                        },
                        new
                        {
                            UserId = new Guid("86f35616-c8ab-4e93-a338-9539046d8361"),
                            Age = (short)81,
                            FirstName = "Elizabeth",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("965a59b6-ee6c-48cb-9897-72402bfab22a"),
                            Age = (short)46,
                            FirstName = "Martina",
                            LastName = "Hall"
                        },
                        new
                        {
                            UserId = new Guid("bdc1d503-00e7-42b5-bcec-2b93c023ed11"),
                            Age = (short)45,
                            FirstName = "Michael",
                            LastName = "Anderson"
                        },
                        new
                        {
                            UserId = new Guid("6be25e47-896b-4d21-823d-d755fec9056e"),
                            Age = (short)39,
                            FirstName = "Richard",
                            LastName = "Watson"
                        },
                        new
                        {
                            UserId = new Guid("8928d192-6dae-42a8-bcf6-dd2a2f3acc6f"),
                            Age = (short)38,
                            FirstName = "Sara",
                            LastName = "Walker"
                        },
                        new
                        {
                            UserId = new Guid("c7898499-541e-4e17-b832-28658338a25e"),
                            Age = (short)26,
                            FirstName = "Michael",
                            LastName = "Johnson"
                        },
                        new
                        {
                            UserId = new Guid("7ca6b6af-86b9-47c4-8110-e1ebe8de7bcd"),
                            Age = (short)77,
                            FirstName = "Jennifer",
                            LastName = "Reed"
                        },
                        new
                        {
                            UserId = new Guid("58a1c3ab-0a7f-49b6-8b02-62c6f2c081d1"),
                            Age = (short)35,
                            FirstName = "Elizabeth",
                            LastName = "Collins"
                        },
                        new
                        {
                            UserId = new Guid("98952330-d835-4867-b855-9471bfc134fc"),
                            Age = (short)79,
                            FirstName = "Richard",
                            LastName = "Johnson"
                        },
                        new
                        {
                            UserId = new Guid("65d024ef-1e91-4c26-93ec-d4e22a6b0c8c"),
                            Age = (short)75,
                            FirstName = "",
                            LastName = "Johnson"
                        },
                        new
                        {
                            UserId = new Guid("ecc46080-4b48-404e-aecd-ad4a2a9da58f"),
                            Age = (short)68,
                            FirstName = "Patricia",
                            LastName = "Garcia"
                        },
                        new
                        {
                            UserId = new Guid("daabab12-5c19-43fe-8be6-1cde9baaadcb"),
                            Age = (short)65,
                            FirstName = "Richard",
                            LastName = ""
                        },
                        new
                        {
                            UserId = new Guid("5dce7098-635a-4719-b155-4e95cbe7fe8c"),
                            Age = (short)20,
                            FirstName = "John",
                            LastName = "Walker"
                        },
                        new
                        {
                            UserId = new Guid("799aa134-1911-4fec-9c62-44bb14a7d9b6"),
                            Age = (short)23,
                            FirstName = "Martina",
                            LastName = "Martin"
                        },
                        new
                        {
                            UserId = new Guid("e3032fcc-f08e-46f6-88dc-7d90c35033da"),
                            Age = (short)71,
                            FirstName = "Elizabeth",
                            LastName = "Washington"
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
