// <auto-generated />
using System;
using JPD.Demo.Service.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JPD.Demo.Service.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190921023721_JPD.Demo.Service.Data.UserContext_v4")]
    partial class JPDDemoServiceDataUserContext_v4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250);

                    b.Property<int>("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<Guid>("UserId");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address","dbo");
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.Property<Guid>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Interest","dbo");
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.HasKey("UserId");

                    b.ToTable("User","dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("52546bc8-c85e-4bf1-b573-b00b6ecbeca2"),
                            Age = (short)78,
                            FirstName = "Evan",
                            LastName = "Watson"
                        },
                        new
                        {
                            UserId = new Guid("330df43a-229c-47ee-a407-99ec1cdb096e"),
                            Age = (short)74,
                            FirstName = "Pedro",
                            LastName = "Walker"
                        },
                        new
                        {
                            UserId = new Guid("4153b8df-5783-4b29-89bd-2bae75427d19"),
                            Age = (short)32,
                            FirstName = "Michael",
                            LastName = "Collins"
                        },
                        new
                        {
                            UserId = new Guid("c2e80493-6eea-4e86-a45c-34ee91349da9"),
                            Age = (short)51,
                            FirstName = "Evan",
                            LastName = "Roberts"
                        },
                        new
                        {
                            UserId = new Guid("4b8b5f47-1640-4db1-954f-9c4c6e764d8f"),
                            Age = (short)38,
                            FirstName = "Richard",
                            LastName = ""
                        },
                        new
                        {
                            UserId = new Guid("ad90f13e-31d0-4dab-8ed1-25b55f455acd"),
                            Age = (short)49,
                            FirstName = "Sara",
                            LastName = "Powell"
                        },
                        new
                        {
                            UserId = new Guid("c66eb1eb-6196-46d1-8e9f-d9350d39f1b8"),
                            Age = (short)68,
                            FirstName = "Richard",
                            LastName = "Watson"
                        },
                        new
                        {
                            UserId = new Guid("97cd9267-9dba-4f0f-bb5e-68bcc4a84a64"),
                            Age = (short)46,
                            FirstName = "John",
                            LastName = "Johnson"
                        },
                        new
                        {
                            UserId = new Guid("9ca06030-5753-4c14-9126-de46cf394a04"),
                            Age = (short)56,
                            FirstName = "William",
                            LastName = "Reed"
                        },
                        new
                        {
                            UserId = new Guid("adcd15fd-005b-4693-a90c-c9d12bf7e1ad"),
                            Age = (short)79,
                            FirstName = "Michael",
                            LastName = "Bennett"
                        },
                        new
                        {
                            UserId = new Guid("4fce29f6-21c5-4f07-85f4-113181c01a5a"),
                            Age = (short)70,
                            FirstName = "Evan",
                            LastName = "Lee"
                        },
                        new
                        {
                            UserId = new Guid("9330c9c8-f638-400f-9363-700bb16e613c"),
                            Age = (short)29,
                            FirstName = "Jennifer",
                            LastName = "Anderson"
                        },
                        new
                        {
                            UserId = new Guid("71e15640-74e2-4227-b47f-bfd28a7f7f57"),
                            Age = (short)63,
                            FirstName = "Pedro",
                            LastName = "Watson"
                        },
                        new
                        {
                            UserId = new Guid("bcd9c6a5-4d72-4b74-91ad-1278fbe7537f"),
                            Age = (short)78,
                            FirstName = "Jessica",
                            LastName = "Anderson"
                        },
                        new
                        {
                            UserId = new Guid("58416c95-7231-41f4-977d-092d82eddd50"),
                            Age = (short)27,
                            FirstName = "Mary",
                            LastName = "Collins"
                        },
                        new
                        {
                            UserId = new Guid("dee91e49-bd8e-483e-a696-f7fa85e2d12d"),
                            Age = (short)62,
                            FirstName = "Martina",
                            LastName = "Bailey"
                        },
                        new
                        {
                            UserId = new Guid("46f0a694-26e0-40aa-a545-12c0d978ce9c"),
                            Age = (short)69,
                            FirstName = "Jennifer",
                            LastName = "Reed"
                        },
                        new
                        {
                            UserId = new Guid("d1c6c8f5-fbdf-41b3-a00e-333147487783"),
                            Age = (short)71,
                            FirstName = "John",
                            LastName = "Anderson"
                        },
                        new
                        {
                            UserId = new Guid("57f75d45-7afa-485a-8996-8a0d9831736d"),
                            Age = (short)45,
                            FirstName = "Jennifer",
                            LastName = "Roberts"
                        },
                        new
                        {
                            UserId = new Guid("9e802fb0-b3db-4282-91bd-22600d42f311"),
                            Age = (short)43,
                            FirstName = "Elizabeth",
                            LastName = "Collins"
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
