// <auto-generated />
using System;
using JPD.Demo.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JPD.Demo.Service.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190921033836_JPD.Demo.Service.Data.UserContext_v7")]
    partial class JPDDemoServiceDataUserContext_v7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250);

                    b.Property<int>("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<Guid>("UserId");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address","dbo");
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.Property<Guid>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Interest","dbo");

                    b.HasData(
                        new
                        {
                            InterestId = new Guid("3e4e8199-9126-4bb1-afa8-593ee05e1b35"),
                            Description = "Reading is my favorite thing to do.",
                            Name = "Reading",
                            UserId = new Guid("286b979d-cff1-46de-a2ab-bba38ec8b675")
                        },
                        new
                        {
                            InterestId = new Guid("2dc91b02-3b18-4004-bd9b-9c18d8660fbe"),
                            Description = "Singing Out Loud, nuff said.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("286b979d-cff1-46de-a2ab-bba38ec8b675")
                        },
                        new
                        {
                            InterestId = new Guid("03f33dac-62ca-4103-9798-494f77b3da2c"),
                            Description = "Mountain Climbing is the best.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("eac5a25b-a9e1-4857-a005-812ca35a53e8")
                        },
                        new
                        {
                            InterestId = new Guid("3da2ce42-8e89-4be3-98d7-cf3beb34181b"),
                            Description = "I wish I was better at Dancing.",
                            Name = "Dancing",
                            UserId = new Guid("eac5a25b-a9e1-4857-a005-812ca35a53e8")
                        },
                        new
                        {
                            InterestId = new Guid("e530548b-b40b-471f-ac9c-97a676cb08c0"),
                            Description = "I enjoy Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("eac5a25b-a9e1-4857-a005-812ca35a53e8")
                        },
                        new
                        {
                            InterestId = new Guid("a413e081-9d3e-469e-aff0-7fbdd5b30e52"),
                            Description = "Painting is the best.",
                            Name = "Painting",
                            UserId = new Guid("2c29d6af-4baf-4160-9a2f-77f7c3f133c8")
                        },
                        new
                        {
                            InterestId = new Guid("3540bd9c-7b6e-4744-bb2d-e20491c62580"),
                            Description = "Gardening, nuff said.",
                            Name = "Gardening",
                            UserId = new Guid("38820f66-b59a-4b5e-875a-45c0ade7a513")
                        },
                        new
                        {
                            InterestId = new Guid("641442fe-68af-4abc-8d3d-f72663b8c214"),
                            Description = "Music, nuff said.",
                            Name = "Music",
                            UserId = new Guid("420bdd5e-b7cc-449a-85cd-379a84625c8d")
                        },
                        new
                        {
                            InterestId = new Guid("78426650-383e-4338-ba97-25c969900289"),
                            Description = "I wish I could do more Reading.",
                            Name = "Reading",
                            UserId = new Guid("420bdd5e-b7cc-449a-85cd-379a84625c8d")
                        },
                        new
                        {
                            InterestId = new Guid("19424d44-442b-4aa8-b53a-3bb7ab4c2e7c"),
                            Description = "Golf, nuff said.",
                            Name = "Golf",
                            UserId = new Guid("420bdd5e-b7cc-449a-85cd-379a84625c8d")
                        },
                        new
                        {
                            InterestId = new Guid("40d035b8-1e6b-4ff4-9924-a45169910c2c"),
                            Description = "Mountain Climbing, nuff said.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("a97614fc-48cd-4343-901c-dc9c9ed38b6d")
                        },
                        new
                        {
                            InterestId = new Guid("701423a1-367e-41fa-bc82-e5678357dcdc"),
                            Description = "Hiking, nuff said.",
                            Name = "Hiking",
                            UserId = new Guid("a97614fc-48cd-4343-901c-dc9c9ed38b6d")
                        },
                        new
                        {
                            InterestId = new Guid("dc9ad9cb-2543-4d3d-a223-71a7be8c3887"),
                            Description = "Tennis, nuff said.",
                            Name = "Tennis",
                            UserId = new Guid("a97614fc-48cd-4343-901c-dc9c9ed38b6d")
                        },
                        new
                        {
                            InterestId = new Guid("96e1841a-31a0-4080-bdeb-88ffd52cbfaa"),
                            Description = "Skiing is my favorite thing to do.",
                            Name = "Skiing",
                            UserId = new Guid("150547b9-edf6-4811-afd2-66dae55eb279")
                        },
                        new
                        {
                            InterestId = new Guid("0f6da3a9-2f08-42b8-a1ee-36a2f16c98c8"),
                            Description = "I not a big fan of Fishing.",
                            Name = "Fishing",
                            UserId = new Guid("150547b9-edf6-4811-afd2-66dae55eb279")
                        },
                        new
                        {
                            InterestId = new Guid("804fb163-0d6f-4b37-b81b-a1304b609ec0"),
                            Description = "I wish I could do more Space Exploration.",
                            Name = "Space Exploration",
                            UserId = new Guid("150547b9-edf6-4811-afd2-66dae55eb279")
                        },
                        new
                        {
                            InterestId = new Guid("68c4c14e-db41-4ef4-9c75-6b8ee55b2177"),
                            Description = "I not a big fan of Gardening.",
                            Name = "Gardening",
                            UserId = new Guid("150547b9-edf6-4811-afd2-66dae55eb279")
                        },
                        new
                        {
                            InterestId = new Guid("114df06e-7aff-431c-b9ba-52a4ef5c8a07"),
                            Description = " is the best.",
                            Name = "",
                            UserId = new Guid("150547b9-edf6-4811-afd2-66dae55eb279")
                        },
                        new
                        {
                            InterestId = new Guid("67905a06-6cfe-4f12-b93d-a35fb4d8dd4a"),
                            Description = "I not a big fan of Space Exploration.",
                            Name = "Space Exploration",
                            UserId = new Guid("6f95f72d-e4e1-4b44-835b-a0ad34dfb57b")
                        },
                        new
                        {
                            InterestId = new Guid("5e1dbedb-341d-4ac4-adc4-865535e0a671"),
                            Description = "I wish I could do more Hiking.",
                            Name = "Hiking",
                            UserId = new Guid("6f95f72d-e4e1-4b44-835b-a0ad34dfb57b")
                        },
                        new
                        {
                            InterestId = new Guid("09694575-3f67-40f5-be7f-fd46a3f41c25"),
                            Description = "Sofware Engineering Rocks!",
                            Name = "Sofware Engineering",
                            UserId = new Guid("6f95f72d-e4e1-4b44-835b-a0ad34dfb57b")
                        },
                        new
                        {
                            InterestId = new Guid("b9f7a556-52a7-4112-9872-f0091b23a9e0"),
                            Description = "Caligraphy, nuff said.",
                            Name = "Caligraphy",
                            UserId = new Guid("6f95f72d-e4e1-4b44-835b-a0ad34dfb57b")
                        },
                        new
                        {
                            InterestId = new Guid("2a941004-01a2-405d-bd3c-146640a5d915"),
                            Description = "I enjoy Space Exploration.",
                            Name = "Space Exploration",
                            UserId = new Guid("1016b697-b91c-48b8-a3d7-614a633a7f0c")
                        },
                        new
                        {
                            InterestId = new Guid("641214db-78a1-4f71-af2c-37ff16314bae"),
                            Description = "Painting, nuff said.",
                            Name = "Painting",
                            UserId = new Guid("1016b697-b91c-48b8-a3d7-614a633a7f0c")
                        },
                        new
                        {
                            InterestId = new Guid("6a6fe07f-e672-4033-951c-144283ed40ab"),
                            Description = "I enjoy .",
                            Name = "",
                            UserId = new Guid("1016b697-b91c-48b8-a3d7-614a633a7f0c")
                        },
                        new
                        {
                            InterestId = new Guid("6e9ef1aa-6989-42e3-879e-6631eab741b0"),
                            Description = "I wish I was better at Traveling.",
                            Name = "Traveling",
                            UserId = new Guid("c8c10d8d-a3e2-47cc-930d-5fa6f7e9490a")
                        },
                        new
                        {
                            InterestId = new Guid("73df6f40-7f9c-4c3c-913c-51689dc6d018"),
                            Description = "Traveling is my favorite thing to do.",
                            Name = "Traveling",
                            UserId = new Guid("c8c10d8d-a3e2-47cc-930d-5fa6f7e9490a")
                        },
                        new
                        {
                            InterestId = new Guid("cf2204fd-11df-48c1-80e6-2b4d2b9e760d"),
                            Description = "I wish I could do more Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("fe499d5f-6958-490e-a17f-ca9783e11d68")
                        },
                        new
                        {
                            InterestId = new Guid("13729409-0eba-41aa-89ef-ef2a23f02a62"),
                            Description = " is my favorite thing to do.",
                            Name = "",
                            UserId = new Guid("fe499d5f-6958-490e-a17f-ca9783e11d68")
                        },
                        new
                        {
                            InterestId = new Guid("823ce0e0-e75c-4b8a-b72e-99fb0ee12630"),
                            Description = "I wish I was better at Painting.",
                            Name = "Painting",
                            UserId = new Guid("fe499d5f-6958-490e-a17f-ca9783e11d68")
                        },
                        new
                        {
                            InterestId = new Guid("239c6732-809f-42b3-84eb-4c0dbfff165b"),
                            Description = "I enjoy Singing Out Loud.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("fe499d5f-6958-490e-a17f-ca9783e11d68")
                        },
                        new
                        {
                            InterestId = new Guid("53a577f3-0d83-46c7-b07d-5e1a234806ba"),
                            Description = "I wish I was better at Music.",
                            Name = "Music",
                            UserId = new Guid("f09707a4-83f8-4f16-8147-e9a6e8b819f9")
                        },
                        new
                        {
                            InterestId = new Guid("3937fbe8-6dae-40d6-a49d-2ebcd60950be"),
                            Description = "Theater, nuff said.",
                            Name = "Theater",
                            UserId = new Guid("f09707a4-83f8-4f16-8147-e9a6e8b819f9")
                        },
                        new
                        {
                            InterestId = new Guid("2f279356-c396-468b-b0ad-49c04df83211"),
                            Description = "I wish I could do more Space Exploration.",
                            Name = "Space Exploration",
                            UserId = new Guid("f09707a4-83f8-4f16-8147-e9a6e8b819f9")
                        },
                        new
                        {
                            InterestId = new Guid("508d1f50-dddb-4cd4-84d0-bcb1e6778d45"),
                            Description = "I wish I was better at Singing Out Loud.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("708e98ab-5375-4013-8d25-fd7fc0c87eea")
                        },
                        new
                        {
                            InterestId = new Guid("f90f2466-b107-4821-b6e7-e9911d50dd3f"),
                            Description = "Painting, nuff said.",
                            Name = "Painting",
                            UserId = new Guid("708e98ab-5375-4013-8d25-fd7fc0c87eea")
                        },
                        new
                        {
                            InterestId = new Guid("08dabf3b-2b3b-401e-9d1d-e88c924fd9ec"),
                            Description = "I enjoy Caligraphy.",
                            Name = "Caligraphy",
                            UserId = new Guid("708e98ab-5375-4013-8d25-fd7fc0c87eea")
                        },
                        new
                        {
                            InterestId = new Guid("a953da57-b0ef-492e-9ce2-04987da51db5"),
                            Description = "Mountain Climbing, nuff said.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("4b2358e1-8293-4789-9113-0c01d30a8820")
                        },
                        new
                        {
                            InterestId = new Guid("18e64788-5432-4702-8da3-d247ecbbaa18"),
                            Description = "I not a big fan of Traveling.",
                            Name = "Traveling",
                            UserId = new Guid("772c4277-8c6e-4c06-ae8e-1d06753c70c9")
                        },
                        new
                        {
                            InterestId = new Guid("c476cb0c-b1c3-461a-b2db-277bf5b8ebc0"),
                            Description = "Traveling is my favorite thing to do.",
                            Name = "Traveling",
                            UserId = new Guid("34ef965e-8339-4c53-86b1-1d3d9f428de4")
                        },
                        new
                        {
                            InterestId = new Guid("acc4217a-9515-4432-8d6c-7e3605de8a3a"),
                            Description = "I enjoy Singing Out Loud.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("34ef965e-8339-4c53-86b1-1d3d9f428de4")
                        },
                        new
                        {
                            InterestId = new Guid("70cf9a32-5934-4f6b-ad52-176f78fb4f2a"),
                            Description = "Singing Out Loud is the best.",
                            Name = "Singing Out Loud",
                            UserId = new Guid("34ef965e-8339-4c53-86b1-1d3d9f428de4")
                        },
                        new
                        {
                            InterestId = new Guid("ef9ff377-2799-43b2-ace2-1a5978beb533"),
                            Description = "I wish I was better at Traveling.",
                            Name = "Traveling",
                            UserId = new Guid("82a77a7b-eb63-4d87-aa9c-7ea637973823")
                        },
                        new
                        {
                            InterestId = new Guid("2f5a7bd8-6b0e-413c-ab93-607661ab180f"),
                            Description = "I enjoy Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("82a77a7b-eb63-4d87-aa9c-7ea637973823")
                        },
                        new
                        {
                            InterestId = new Guid("99f9eda0-56de-4cf7-ba2c-892e5333587f"),
                            Description = "I enjoy Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("82a77a7b-eb63-4d87-aa9c-7ea637973823")
                        },
                        new
                        {
                            InterestId = new Guid("2ec386cb-9aec-4e3a-acc5-63d30c477f3c"),
                            Description = "I wish I could do more .",
                            Name = "",
                            UserId = new Guid("8d8ad1f6-42c9-4b7d-938d-38147ccbe8e0")
                        },
                        new
                        {
                            InterestId = new Guid("6897bb14-45ae-46f5-bfbf-85f2ff2f2e88"),
                            Description = "I not a big fan of Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("300adbce-d6ed-4414-ae27-bdab4386f37c")
                        },
                        new
                        {
                            InterestId = new Guid("0ceacdb8-281b-4696-9f97-26da3c5f68cf"),
                            Description = "Bicycling is the best.",
                            Name = "Bicycling",
                            UserId = new Guid("300adbce-d6ed-4414-ae27-bdab4386f37c")
                        },
                        new
                        {
                            InterestId = new Guid("3f7e7185-fdce-4f92-a3be-b95103384e58"),
                            Description = "Fishing is my favorite thing to do.",
                            Name = "Fishing",
                            UserId = new Guid("300adbce-d6ed-4414-ae27-bdab4386f37c")
                        },
                        new
                        {
                            InterestId = new Guid("c75b9c94-db9d-433a-906e-6a5de542a4c7"),
                            Description = "Painting, nuff said.",
                            Name = "Painting",
                            UserId = new Guid("b5a4c1d4-ec86-49d0-92c1-90b268ae1a45")
                        },
                        new
                        {
                            InterestId = new Guid("253edbc5-6352-46cb-a61c-c521998c43d8"),
                            Description = "I not a big fan of Mountain Climbing.",
                            Name = "Mountain Climbing",
                            UserId = new Guid("b5a4c1d4-ec86-49d0-92c1-90b268ae1a45")
                        },
                        new
                        {
                            InterestId = new Guid("71049110-490f-45c1-a534-1eb31e7b42d0"),
                            Description = "I wish I could do more Skiing.",
                            Name = "Skiing",
                            UserId = new Guid("b5a4c1d4-ec86-49d0-92c1-90b268ae1a45")
                        },
                        new
                        {
                            InterestId = new Guid("85eacfc1-af1f-44c7-95ba-23e55a973197"),
                            Description = "I wish I could do more Traveling.",
                            Name = "Traveling",
                            UserId = new Guid("b5a4c1d4-ec86-49d0-92c1-90b268ae1a45")
                        },
                        new
                        {
                            InterestId = new Guid("4b8c32e7-0872-4a9a-ad28-295cfb830e6d"),
                            Description = "I wish I could do more Music.",
                            Name = "Music",
                            UserId = new Guid("b5a4c1d4-ec86-49d0-92c1-90b268ae1a45")
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75);

                    b.HasKey("UserId");

                    b.ToTable("User","dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("286b979d-cff1-46de-a2ab-bba38ec8b675"),
                            Age = (short)69,
                            FirstName = "Charles",
                            LastName = "Powell"
                        },
                        new
                        {
                            UserId = new Guid("eac5a25b-a9e1-4857-a005-812ca35a53e8"),
                            Age = (short)62,
                            FirstName = "Barbara",
                            LastName = "Diaz"
                        },
                        new
                        {
                            UserId = new Guid("2c29d6af-4baf-4160-9a2f-77f7c3f133c8"),
                            Age = (short)73,
                            FirstName = "Catalina",
                            LastName = ""
                        },
                        new
                        {
                            UserId = new Guid("38820f66-b59a-4b5e-875a-45c0ade7a513"),
                            Age = (short)77,
                            FirstName = "John",
                            LastName = "Johnson"
                        },
                        new
                        {
                            UserId = new Guid("420bdd5e-b7cc-449a-85cd-379a84625c8d"),
                            Age = (short)39,
                            FirstName = "Michael",
                            LastName = "Lee"
                        },
                        new
                        {
                            UserId = new Guid("a97614fc-48cd-4343-901c-dc9c9ed38b6d"),
                            Age = (short)48,
                            FirstName = "Mary",
                            LastName = "Garcia"
                        },
                        new
                        {
                            UserId = new Guid("150547b9-edf6-4811-afd2-66dae55eb279"),
                            Age = (short)42,
                            FirstName = "Richard",
                            LastName = "Rivera"
                        },
                        new
                        {
                            UserId = new Guid("6f95f72d-e4e1-4b44-835b-a0ad34dfb57b"),
                            Age = (short)55,
                            FirstName = "William",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("1016b697-b91c-48b8-a3d7-614a633a7f0c"),
                            Age = (short)44,
                            FirstName = "Sara",
                            LastName = "Garcia"
                        },
                        new
                        {
                            UserId = new Guid("c8c10d8d-a3e2-47cc-930d-5fa6f7e9490a"),
                            Age = (short)75,
                            FirstName = "Juan",
                            LastName = "Clark"
                        },
                        new
                        {
                            UserId = new Guid("fe499d5f-6958-490e-a17f-ca9783e11d68"),
                            Age = (short)81,
                            FirstName = "Linda",
                            LastName = "Walker"
                        },
                        new
                        {
                            UserId = new Guid("f09707a4-83f8-4f16-8147-e9a6e8b819f9"),
                            Age = (short)76,
                            FirstName = "Martina",
                            LastName = "Bennett"
                        },
                        new
                        {
                            UserId = new Guid("708e98ab-5375-4013-8d25-fd7fc0c87eea"),
                            Age = (short)37,
                            FirstName = "Evan",
                            LastName = "Lee"
                        },
                        new
                        {
                            UserId = new Guid("4b2358e1-8293-4789-9113-0c01d30a8820"),
                            Age = (short)33,
                            FirstName = "Jennifer",
                            LastName = "Walker"
                        },
                        new
                        {
                            UserId = new Guid("772c4277-8c6e-4c06-ae8e-1d06753c70c9"),
                            Age = (short)27,
                            FirstName = "Jessica",
                            LastName = "Hall"
                        },
                        new
                        {
                            UserId = new Guid("34ef965e-8339-4c53-86b1-1d3d9f428de4"),
                            Age = (short)84,
                            FirstName = "John",
                            LastName = "Hayes"
                        },
                        new
                        {
                            UserId = new Guid("82a77a7b-eb63-4d87-aa9c-7ea637973823"),
                            Age = (short)27,
                            FirstName = "John",
                            LastName = "Collins"
                        },
                        new
                        {
                            UserId = new Guid("8d8ad1f6-42c9-4b7d-938d-38147ccbe8e0"),
                            Age = (short)28,
                            FirstName = "Thomas",
                            LastName = "Diaz"
                        },
                        new
                        {
                            UserId = new Guid("300adbce-d6ed-4414-ae27-bdab4386f37c"),
                            Age = (short)42,
                            FirstName = "",
                            LastName = "Watson"
                        },
                        new
                        {
                            UserId = new Guid("b5a4c1d4-ec86-49d0-92c1-90b268ae1a45"),
                            Age = (short)30,
                            FirstName = "Pedro",
                            LastName = "Hayes"
                        });
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Address", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JPD.Demo.Service.Entities.Interest", b =>
                {
                    b.HasOne("JPD.Demo.Service.Entities.User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
